#Vagrant.require_plugin "vagrant-windows"

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "win2012r2x64"
  # Max time to wait for the guest to shutdown
  config.windows.halt_timeout = 20
  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  # Configure base box parameters
  config.vm.guest = :windows
  # Port forward WinRM and RDP
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  #config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"

  # This shell provisioner installs chocolatey and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "shell/windows/main.cmd"
  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  #config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "provision.pp"
    puppet.module_path = "puppet/modules"
  end

  # Use the host's DNS resolver
  config.vm.provider "virtualbox" do |v| 
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
